apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: qa-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - chaos-mesh
    labelSelectors:
      'app': 'nginx'